-- drop db if already have 
 DROP DATABASE IF EXISTS ECommerceAdminDb;

-- 1. Create EF Core History Table
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- 2. Create Independent Tables
CREATE TABLE "AuditLogs" (
    "Id" uuid NOT NULL,
    "UserId" text,
    "UserName" text,
    "Action" text NOT NULL,
    "EntityName" text,
    "EntityId" text,
    "IpAddress" text,
    "Details" text,
    "UserAgent" text,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(255),
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "NormalizedEmail" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "OrderStatuses" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(255),
    CONSTRAINT "PK_OrderStatuses" PRIMARY KEY ("Id")
);

CREATE TABLE "PaymentMethods" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(255),
    CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id")
);

CREATE TABLE "PaymentStatuses" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    CONSTRAINT "PK_PaymentStatuses" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" text NOT NULL,
    "Description" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "UserLoginHistories" (
    "Id" uuid NOT NULL,
    "UserId" text,
    "UserName" text,
    "Action" text NOT NULL,
    "EntityName" text,
    "EntityId" text,
    "IpAddress" text,
    "Details" text,
    "UserAgent" text,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserLoginHistories" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLogin" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "PhotoProfile" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- 3. Create Dependent Tables (Foreign Keys)
CREATE TABLE "Products" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "Price" numeric(18,2) NOT NULL,
    "ImageUrl" character varying(500),
    "Status" integer NOT NULL,
    "Stock" integer NOT NULL,
    "CategoryId" uuid NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Addresses" (
    "Id" uuid NOT NULL,
    "CustomerId" text NOT NULL,
    "Street" character varying(200) NOT NULL,
    "City" character varying(100) NOT NULL,
    "Province" character varying(100) NOT NULL,
    "PostalCode" character varying(20) NOT NULL,
    "Country" character varying(100) NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RolePermissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "Id" uuid NOT NULL,
    "Code" text,
    "OrderStatusId" uuid NOT NULL,
    "ShippingAddressId" uuid,
    "OrderDate" timestamp with time zone NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "CustomerId" text NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Addresses_ShippingAddressId" FOREIGN KEY ("ShippingAddressId") REFERENCES "Addresses" ("Id"),
    CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_OrderStatuses_OrderStatusId" FOREIGN KEY ("OrderStatusId") REFERENCES "OrderStatuses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrderDetails" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_OrderDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderDetails_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "PaymentMethodId" uuid NOT NULL,
    "PaymentStatusId" uuid NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "TransactionId" character varying(255),
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payments_PaymentMethods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payments_PaymentStatuses_PaymentStatusId" FOREIGN KEY ("PaymentStatusId") REFERENCES "PaymentStatuses" ("Id") ON DELETE CASCADE
);

-- 4. Create Indexes
CREATE INDEX "IX_Addresses_CustomerId" ON "Addresses" ("CustomerId");
CREATE INDEX "IX_OrderDetails_OrderId" ON "OrderDetails" ("OrderId");
CREATE INDEX "IX_OrderDetails_ProductId" ON "OrderDetails" ("ProductId");
CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
CREATE INDEX "IX_Orders_OrderStatusId" ON "Orders" ("OrderStatusId");
CREATE INDEX "IX_Orders_ShippingAddressId" ON "Orders" ("ShippingAddressId");
CREATE INDEX "IX_Payments_OrderId" ON "Payments" ("OrderId");
CREATE INDEX "IX_Payments_PaymentMethodId" ON "Payments" ("PaymentMethodId");
CREATE INDEX "IX_Payments_PaymentStatusId" ON "Payments" ("PaymentStatusId");
CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
CREATE INDEX "IX_RolePermissions_RoleId" ON "RolePermissions" ("RoleId");
CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");
CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");

-- Record the migration so EF Core knows it was applied
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231024000000_InitialCreate', '8.0.0');